site_name: Mastering the Marketplace
site_url: https://microsoft.github.io/Mastering-the-Marketplace/
repo_url: https://github.com/microsoft/Mastering-the-Marketplace
repo_name: microsoft/Mastering-the-Marketplace
edit_uri: ''
extra_css: 
    - stylesheets/extra.css

nav:
  - Courses by offer type:
    - Azure Managed Applications: '/Mastering-the-Marketplace/ama/'
    - Container offers for K8s apps: '/Mastering-the-Marketplace/container/'
    - SaaS: '/Mastering-the-Marketplace/saas/'
    - Virtual Machines: '/Mastering-the-Marketplace/vm/'
  - Bonus content:
    - Quick Startss: '/Mastering-the-Marketplace/quick-starts/'
    - SaaS Accelerator: '/Mastering-the-Marketplace/saas-accelerator/'
    - Partner Center: '/Mastering-the-Marketplace/partner-center/'
    - Private offers: '/Mastering-the-Marketplace/partner-center/private-offers'
    - Marketplace Minis: '/Mastering-the-Marketplace/misc/marketplace-minis'
  - Events:
    - Webinars: 'https://aka.ms/MTMwebinars'
    - Live workshops: 'https://aka.ms/MTMworkshops'
    - Office Hours: 'https://aka.ms/MTMofficehours'
  - More resources:
    - ⚙️ Technical Accelerators: '/Mastering-the-Marketplace/misc/accelerators'
    - 🌐 Choose your offer type: '/Mastering-the-Marketplace/misc/select-offer-type'
    - 🚦 Learning paths: '/Mastering-the-Marketplace/learning-paths/'
    - 🔎 For your customers: '/Mastering-the-Marketplace/learning-paths/customer'
    - 🗒️ Site change log: '/Mastering-the-Marketplace/misc/change-log'
    - ✉️ Contact us: 'https://forms.office.com/r/0gCrzhSMkw'
  
theme:
  features:
    - navigation.sections
    - navigation.expand
  name: material
  custom_dir: overrides
  palette: 
    primary: '#0078D4'
    accent: 'light blue'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/microsoft
  favicon: favicon.ico

extra: 
  homepage: https://microsoft.github.io/Mastering-the-Marketplace/
  generator: false
  analytics:
    provider: google
    property: G-QFBKKPKXNV

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"
  # - pymdownx.emoji:
        # emoji_index: !!python/name:materialx.emoji.twemoji
        # emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search:
        indexing: 'titles'
